spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/ve_db?characterEncoding=utf8&
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-enums-package: com.vshop.veat.enums
server:
  servlet:
    context-path: /sell
