spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/ve_db?characterEncoding=utf8&

mybatis:
  mapper-locations: classpath:/mapper/*.xml